---

- name: JunOS Interfaces RPC
  hosts: ro-test
  gather_facts: no
  connection: local
  tasks:


    - junos_rpc:
        output: xml
        provider: "{{ ansible_provider }}"
        rpc: get-interface-information
        args:
          detail: true
      register: rpc

    - copy:
        content: "{{ rpc['xml'] | replace('\\n','\n') }}"
        dest: "out/{{ inventory_hostname }}_rpc_interfaces.xml"


# vim:ft=ansible:
