---

- name: Junos BGP RPC
  hosts: ro-test
  gather_facts: no
  connection: local
  tasks:

    - junos_rpc:
        output: xml
        provider: "{{ ansible_provider }}"
        rpc: get-bgp-summary-information
      register: rpc

    - copy:
        content: "{{ rpc['xml'] | replace('\\n','\n') }}"
        dest: "out/{{ inventory_hostname }}_rpc_bgp_summary.xml"

    - junos_rpc:
        output: xml
        provider: "{{ ansible_provider }}"
        rpc: get-bgp-neighbor-information
      register: rpc

    - copy:
        content: "{{ rpc['xml'] | replace('\\n','\n') }}"
        dest: "out/{{ inventory_hostname }}_rpc_bgp_neighbor.xml"


# vim:ft=ansible:
