---

- name: JunOS routes RPC
  hosts: ro-test
  gather_facts: no
  connection: local
  tasks:

    - name: Call get-route-information
      junos_rpc:
        output: xml
        provider: "{{ ansible_provider }}"
        args:
          #          all:
            #detail:
        rpc: get-route-information
      register: rpc

    - name: Write get-route-information
      copy:
        content: "{{ rpc['xml'] | replace('\\n','\n')}}"
        dest: "out/{{ inventory_hostname }}_rpc_routes.xml"


    - name: Call get-route-summary-information
      junos_rpc:
        output: xml
        provider: "{{ ansible_provider }}"
        rpc: get-route-summary-information
      register: rpc

    - name: Write get-route-summary-information
      copy:
        content: "{{ rpc['xml'] | replace('\\n','\n')}}"
        dest: "out/{{ inventory_hostname }}_rpc_routes_summary.xml"

# vim:ft=ansible:
