---

- name: JunOS Environment RPC
  hosts: ro-test
  gather_facts: no
  connection: local
  tasks:

    - junos_rpc:
        output: xml
        provider: "{{ ansible_provider }}"
        rpc: get-environment-information
      register: rpc

    - copy:
        content: "{{ rpc['xml'] | replace('\\n','\n') }}"
        dest: "out/{{ inventory_hostname }}_rpc_environment.xml"

# vim:ft=ansible:
